### PR TITLE
fixes #239

### LINKED ISSUE #239: Broken link in mentoring docs - Choosing solution to mentor
The link at the end of [this](https://github.com/exercism/docs/blob/main/mentoring/choosing_a_solution.md) page is broken

### PR DESCRIPTION
**Pull request by JaPrad**
Fixed the broken link

### CODE REVIEW

**Comment by iHiD** [comment]
Hi, the correct link is `/docs/mentoring/how-to-give-great-feedback`. Pls change to that. Thanks.

**Comment by JaPrad** [comment]
Hello @iHiD. Implemented your instructions - but shows error 404 on clicking the link (after commit).

**Comment by JaPrad** [comment]
I see that the file is named `how_to_give_great_feedback.md` - (underscores instead of hyphens). Does that make a difference?

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@JaPatGitHub The links are interpreted differently on the website. What you have now is correct.

**Pull request merged**
