### PR TITLE
Add stories for `top-secret` and `new-passport`

### PR DESCRIPTION
**Pull request by jiegillet**
I have added two stories for concept exercises that we have recently added on the Elixir track.

This is my first contribution of this type, so any feedback is greatly appreciated.

@angelikatyborska I added Top Secret to the mix, I hope that's OK, please have a look.
@BethanyG I finally got around to adding the story.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
Great! I'll let @angelikatyborska and @BethanyG review too.

**Review by angelikatyborska — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
The contents look good, so I've merged this (Angelika approved). Let me know if you think there is still room for improvement @BethanyG.

@junedev We now have two new stories. Should we update the stories README document manually, or is there a script?

**Comment by junedev** [comment]
@ErikSchierboom Since these stories already existed in the repo, they are already part of the table I made. I am currently not parsing the story files, so this PR doesn't change the outcome.

In general, there is a script though that I can run every now and then.

**Comment by ErikSchierboom** [comment]
Perfect, thanks!

**Pull request merged**
