### PR TITLE
Add badge ideas for blocking/being blocked

### PR DESCRIPTION
**Pull request by SaschaMann**
It's unlikely that you'll get along with absolutely everyone. Therefore instead of being frustrated by it, we should celebrate it as an achievement and accept that this is normal.

### CODE REVIEW

**Comment by iHiD** [comment]
Ha.

There's actually no-way to know if someone has blocked you, so I'm not sure I want to leak that information (as it could lead to more negative reaction). I'll have a think though!

**Comment by ErikSchierboom** [comment]
> Therefore instead of being frustrated by it, we should celebrate it as an achievement and accept that this is normal.

I'm not sure about this. It is indeed normal to not get along with everyone, but making it a badge incentives people to block people or being blocked, which I don't think we want to do.

As Jeremy said, it also leaks information, where someone could theoretically infer they're being blocked by having had just one mentor and then getting the being blocked badge.

**Comment by iHiD** [comment]
Yeah, I'm saying no to this one :)

**Comment by SaschaMann** [comment]
This should be listed in the `Rejected` category then, not closed. #341 fixes it.

**Pull request closed without merging**
