### PR TITLE
Add missing "non-blank" linting rule

### PR DESCRIPTION
**Pull request by ee7**
With this PR, we now specify in `lint.md` that all kebab strings are non-blank:
```
$ git grep --break --heading 'kebab'
building/configlet/lint.md
52:- The `"slug"` value must be a non-empty, non-blank, lowercased string using kebab-case
75:- The `"exercises.concept[].slug"` value must be a non-empty, non-blank, lowercased string using kebab-case
87:- The `"exercises.concept[].concepts"` values must be non-empty, non-blank, lowercased strings using kebab-case
94:- The `"exercises.concept[].prerequisites"` values must be non-empty, non-blank, lowercased strings using kebab-case
105:- The `"exercises.practice[].slug"` value must be a non-empty, non-blank, lowercased string using kebab-case
119:- The `"exercises.practice[].practices"` values must be non-empty, non-blank, lowercased strings using kebab-case
126:- The `"exercises.practice[].prerequisites"` values must be non-empty, non-blank, lowercased strings using kebab-case
134:- The `"exercises.foregone"` values must be non-empty, non-blank, lowercased strings using kebab-case
142:- The `"concepts[].slug"` value must be a non-empty, non-blank, lowercased string using kebab-case

building/tracks/concept-exercises.md
476:1. Use [kebab-case][kebab-case].
489:- `TimFromMarketing`: does not use kebab-case (i.e. `tim-from-marketing`)
496:[kebab-case]: https://en.wiktionary.org/wiki/kebab_case

building/tracks/config-json.md
10:- `slug`: the track's language as a lowercased, kebab-case string (e.g. `"csharp"`) (required)
35:- `%{kebab_slug}`: the `kebab-case` exercise slug (e.g. `bit-manipulation`)
83:- `slug`: the exercise's slug, which is a lowercased, kebab-case string. The slug must be unique across all concept _and_ practice exercise slugs within the track
137:- `slug`: the exercise's slug, which is a lowercased, kebab-case string. The slug must be unique across all concept _and_ practice exercise slugs within the track
215:- `slug`: the concept's slug, which is a lowercased, kebab-case string. The slug must be unique across all concepts within the track
```

### CODE REVIEW

**Comment by iHiD** [comment]
How does an empty string differ from a blank string? (in Ruby, they're the same thing for example)

**Comment by ee7** [comment]
We're using the definitions:
- an "empty string" is zero-length, `""`
- a "blank string" is a non-empty string that is whitespace-only, e.g. `"      "`

**Comment by iHiD** [comment]
Thanks.

Is there any situation where we allow blank strings, or could we define them to be synonyms?

Also are those definitions somewhere in the file (I can't see them) - if not could we add them pls?

**Comment by ee7** [comment]
> Is there any situation where we allow blank strings, or could we define them to be synonyms?

Currently, nearly every "regular string" in the spec is specified to be both non-empty and non-blank. The exception is:

> - The `"language_versions"` key is optional
> - The `"language_versions"` value must be a string

But that might be an oversight in the spec, and currently `configlet lint` produces an error for an optional key that has the value of the empty string.

> Also are those definitions somewhere in the file

Not currently.

> if not could we add them pls?

We could, but we might be able to find a better wording while we're at it. I think it could be nice to condense

> - The `"language"` value must be a non-empty, non-blank string
> - The `"slug"` value must be a non-empty, non-blank, lowercased string using kebab-case

down to something like
> - The `"language"` value must be a non-trivial string¹
> - The `"slug"` value must be a kebab-case string²

> Glossary:
> 1. Non-trivial string: a string that has at least one non-whitespace character.
> 2. kebab-case string: a string that contains only characters in the range `[a-z0-9]`, optionally separated by dashes (e.g. "two-fer"). It must match the regular expression: `^[a-z0-9]+(-[a-z0-9]+)*$`

I've tried to do exactly that in #115. That PR also resolves the issue that this PR addressed, so I'm closing this one.

**Comment by iHiD** [comment]
Thanks :)

**Pull request closed without merging**
