### PR TITLE
Fix links to "sibling" .md files

### PR DESCRIPTION
**Pull request by lynxnake**
So that they will open ok from github

### CODE REVIEW

**Comment by ee7** [comment]
The links are designed to work on the website (here, https://exercism.org/docs/building/tooling/test-runners - where the links do work). It's expected that they don't work on GitHub. I know it's confusing - sorry.

From the [`README.md`](https://github.com/exercism/docs/blob/f0d062b57a3b17f3d513fa57c204e88e7a47241e/README.md) in this repo:

> Please note that these docs are meant to be read at https://exercism.org/docs - not in this website. Links in this repository are relative to the website, not internally in this repo.

@ErikSchierboom I think we'll keep running into this problem. What do you think about pinning an issue in this repo to make the situation more visible?

Previously: https://github.com/exercism/docs/pull/158#issuecomment-867571042, https://github.com/exercism/docs/issues/162, https://github.com/exercism/docs/issues/163, https://github.com/exercism/docs/issues/230, https://github.com/exercism/docs/pull/234, https://github.com/exercism/docs/issues/243, https://github.com/exercism/docs/issues/312, https://github.com/exercism/docs/issues/350, https://github.com/exercism/docs/pull/351, https://github.com/exercism/docs/issues/360, https://github.com/exercism/docs/issues/386

**Comment by lynxnake** [comment]
Thanks, closing it

**Comment by ErikSchierboom** [comment]
> What do you think about pinning an issue in this repo to make the situation more visible?

That sounds like a good idea.

**Comment by ee7** [comment]
> That sounds like a good idea.

I've created #397.

**Pull request closed without merging**
