### PR TITLE
Mentoring queue image and markup

### PR DESCRIPTION
**Pull request by Nerwosolek**
I have added a mentoring queue image to _.imgs_ folder with user details blurred for privacy reasons.
Also added proper markup in _mentoring/choosing_a_solution.md_

### CODE REVIEW

**Comment by Nerwosolek** [comment]
This regards issue #172 
(I hope I do communication right).

**Comment by iHiD** [comment]
@Nerwosolek Great. Thank you! I've tweaked things slightly as I need to manually put images on S3 atm, but will deploy it with that change made :)

**Comment by Nerwosolek** [comment]
Happy to help and learn OSS contribution!

**Comment by Nerwosolek** [comment]
> @Nerwosolek Great. Thank you! I've tweaked things slightly as I need to manually put images on S3 atm, but will deploy it with that change made :)

So, how should I do next image uploads (when necessary) to be convenient for you to copy them to S3?

**Comment by iHiD** [comment]
For now, what you did is absolutely fine. We need auto-s3 syncing and some other stuff, but I need to think that through with @ErikSchierboom to work it out.

As one piece of advise, when you make contributions to OSS, you'll find it better to use a branch on your local repository. You submitted this one from your `main` branch, which is likely to cause you trouble! This is a good document to explain it :) https://guides.github.com/introduction/flow/

**Pull request merged**
