### PR TITLE
Require `key_features[].title` to be Title Case

### PR DESCRIPTION
**Pull request by ee7**
Addressing https://github.com/exercism/docs/pull/117#issuecomment-819454151

Is there anything else that should be in Title Case?

### CODE REVIEW

**Comment by iHiD** [comment]
At the risk of everyone hating me, I actually think Key Features' titles should be Sentence Case.

**Comment by SaschaMann** [comment]
I prefer the looks of title case on the python/julia track over the sentence case features the elixir track uses.

But most are single words so it's rarely relevant.

**Comment by ErikSchierboom** [comment]
Hmmm, disagreement then! I don't massively care if it's Sentence case or Title Case to be honest, but I _don't_ want people to use other cases (lowercase, snake_case, kebab-case), so maybe we could say Sentence Case _or_ Title Case? Or is that too much of a compromise.

**Comment by iHiD** [comment]
Let's go for sentence case for the key features.

**Comment by ErikSchierboom** [comment]
@ee7 could you update?

**Comment by ErikSchierboom** [comment]
Closed in favor of #334

**Pull request closed without merging**
