### PR TITLE
Add test generator to track tooling

### PR DESCRIPTION
**Pull request by mk-mxp**
As discussed in [the forum](https://forum.exercism.org/t/test-generators-for-tracks/10615).

This my first approach to documenting the test generator information for future contributors. I am very open for improvements, be it language, structure or the place it should live in the docs.

@ErikSchierboom

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
Thanks for this! It's quite a big document, so I think the best approach is to merge this and then I'll double some tweaks in a follow-up PR. The only thing this requires to be added is to have a new entry in https://github.com/exercism/docs/blob/main/building/config.json.

**Comment by ErikSchierboom** [comment]
Thanks!

**Comment by ErikSchierboom** [comment]
> Some tracks also create tests for concept exercises from a similar track-owned data source.

@mk-mxp What tracks do this?

**Comment by mk-mxp** [comment]
> > Some tracks also create tests for concept exercises from a similar track-owned data source.
> 
> @mk-mxp What tracks do this?

I think I mixed it up in my memory from:

- [Python's `additional_tests.json`](http://forum.exercism.org/t/test-generators-for-tracks/10615/11) to extend from problem specs
- [Crystal's concept templates](https://github.com/exercism/crystal/blob/main/exercises/concept/chess-game/.meta/template.md) for concept exercises (I now see this is for something different)
- and some own thoughts about test generator usage for concept exercises

Should I remove that or make more into a suggestion: "Tracks may also create tests for concept exercises from a similar track-owned data source."?

**Comment by ErikSchierboom** [comment]
I'll remove it in a future PR  :)

**Comment by BNAndras** [comment]
`Each language may have its own Test Generator, written in that language.` should be updated in a future PR to something like `Each language may have its own Test Generator, often written in that language.`

As written, I interpret that as being a requirement that a test generator be written in the same language as a track. Some tracks may choose not to do this for a variety of reasons.

**Comment by ErikSchierboom** [comment]
I'm working on a revised version

**Pull request merged**
