### PR TITLE
adding paradigms

### PR DESCRIPTION
**Pull request by axtens**
When looking up what vbnet has as its [Paradigms ](https://en.wikipedia.org/wiki/Visual_Basic_.NET) I noticed that we don't have all the categories that the Wikipedia article has for vbnet.

I haven't included reflective.

### CODE REVIEW

**Comment by iHiD** [comment]
Thanks. We've only Included categories that are relatively well-shared between tracks (otherwise they don't hold much value as filters). I don't know how well-shared these are. **Would any other tracks want to use these?** 

(cc @exercism/track-maintainers)

**Comment by ynfle** [comment]
Generics are fairly common across languages. [The Wikipedia article](https://en.wikipedia.org/wiki/Generic_programming) mentions  Ada, C#, Delphi, Eiffel, F#, Java, Nim, Python, Rust, Swift, TypeScript, Visual Basic .NET, ML, Scala, Julia, Haskell and templates in C++ and D.

However, I'm not sure if it's considered a paradigm.

**Comment by ErikSchierboom** [comment]
There is a mention of generic programming on the https://en.wikipedia.org/wiki/Programming_paradigm, but then again there is a huge number of paradigms listed there. As @iHiD said, our goal was not be exhaustive, but to just have the most commonly used paradigms. Personally, I don't feel like generic programming is on the same level as the existing paradigms. I like event-driven more, but how many tracks would check that box?

**Comment by booniepepper** [comment]
I like event-driven. _(Edit: Although in my experience this is more about the way programs are structured than languages themselves. I think VB .NET as an example is event-driven only when you're writing for applications - maybe not when doing exercises on exercism? Dart, or even Java via AWT or JavaScript when run in a browser are "event driven")_ I think languages where events are actually core to languages is when they have something like a strong actor-based programming model built directly in to the language (consider [Erlang's `spawn/3` builtin function and `receive` keyword](https://learnyousomeerlang.com/designing-a-concurrent-application))

Generics (in my opinion) are not a programming paradigm. They are a powerful tool for achieving certain types of polymorphism. They are not the only tool -- in fact, in most languages that have generics, they may a best way to solve problems, generics are not the only tool. I'd put generics into the same category as function overloading, row polymorphism, duck typing, or structural typing (etc etc). Not sure I'd elevate any of these to a "paradigm" so much as intermediate-to-advanced features of a language.

**Comment by booniepepper** [comment]
P.S. small plug for [concatenative programming](http://evincarofautumn.blogspot.com/2012/02/why-concatenative-programming-matters.html). (Although it would apply only to Forth and Factor)

I can add these outside this particular PR though

**Comment by ghost** [comment]
There’s exhaustive lists defining paradigms, but I’ve rarely come across material meant to put a cohesive context to very dry technical reading. Even researching the Actor Model, I found few viable practical implementations of the model to demonstrate why we use them. I’ve been working on event driven prototyping for a nodejs client for my agricultural IoT Project. I’ve been fixing to use it as a demo for teaching about recursive event looping. I’d be happy to draft a paper outlining what I did. JS is as close to pseudo code you can get before hitting Perl. But no one thinks Perl is cool, except me and 2.5% of the internet.

**Comment by bitfield** [comment]
A good way to get traction with PRs like this is to explain the _problem_ that it solves (that is, the problem encountered by Exercism users looking to select a language track). Without that, it's difficult for reviewers to see why this change is worth making, even though it may be perfectly apparent to the proposer.

**Comment by ErikSchierboom** [comment]
Having looked into this a bit, I don't think the new paradigms offer much value to us as their primary goal is for them to be used to filter tracks on. I'm therefore leaning towards closing this issue. If someone disagrees, let me know and we can discuss. Thanks for opening the PR @axtens.

**Pull request closed without merging**
