### PR TITLE
Add examples for size labels

### PR DESCRIPTION
**Pull request by junedev**
I think it would be good to have examples for which size label to use for which contributions. I noticed that maintainers often give their own work a lower size label than what they would give other contributors. Maybe these examples help that people label themselves and others fairly.

Happy to discuss what examples to use in more detail if needed, I mainly wanted to put this PR out as a starting point.

### Open Questions
* Do we want more than one example for each category? (not super easy to do formatting wise, lists in Markdown is a bit of a pain so I kept it to one example for now)
* There is the following text right above the table, is that still correct now that we have the more fine grained labels? It sounds a bit like it was meant for the old version where there was only small/medium/large. I am fine with keeping it, just wanted to make sure it isn't an artifact of an older version of the table.
  > In exceptional circumstances (either tiny PRs changing a few lines, or large PRs that will have taken a greater than normal of effort) is possible to award more (or less) reputation for a merged pull request by adding one of the following labels to the pull request

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
This is an great improvement, thanks!

> Do we want more than one example for each category? (not super easy to do formatting wise, lists in Markdown is a bit of a pain so I kept it to one example for now)

More examples _would_ be great. Maybe just separate them with a comma? Would that work?

> There is the following text right above the table, is that still correct now that we have the more fine grained labels? It sounds a bit like it was meant for the old version where there was only small/medium/large. I am fine with keeping it, just wanted to make sure it isn't an artifact of an older version of the table.

I think we need to tweak that text a bit. E.g. the "In exceptional circumstances" bit is really not true anymore, as I think most PRs are actually tiny or small.

**Comment by junedev** [comment]
FYI I asked on Slack whether others have ideas for good examples as well. Let's give it a couple of days.

**Comment by BethanyG** [comment]
So I know this will probably be viewed as problematic, but my "scale" is a little bit fuzzy around these.  For example, if the PR is coming from a first-time contributor - even if it's pretty small - I typically award 12 (med) for two reasons:

1.  Doing your first PR to a project is **hard**. There may be docs to read, issues to go through, and multiple things to set up.
2. Doing your first PR to a project is **intimidating** - so getting the "average" credit is a way to be encouraging.

Likewise, for the Python track, writing test cases can be hard.  We use some funky parameterization and enumeration tricks as well as context handlers -- so adding a test case from scratch might get more than `small`.  The same goes for editing our JinJa templates -- making a coherent edit there requires that someone know or learn JinJa - so it's not always as simple as a typo. 

Just the things that came to mind, not hard and fast....

| Label            	| Reputation 	| Example                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       	|
|------------------	|------------	|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| `x:size/tiny`    	| 3          	| <ul> <li>  Fixing a single typo (includes adding punctuation) <li>  Removing an extra blank lines <li>  Adding a missing `EOL` at the end of a file or files <li>  Adding/changing a header level <li>  Fixing a single link <li>  Changing a single docstring/adding a single comment to code <li>  Changing an in-line link to a reflink <li>  Running prettier to auto-format </ul>                                                                                                                                                                                                                                                                                                                                                        	|
| `x:size/small`   	| 5          	| <ul> <li>  Fixing a single test case/task/code example <li>  Fixing multiple typos in a single file <li>  Fixing multiple headers in a file <li>  Fixing multiple broken links in a file <li>  Adding clarifying language of a few lines to a file <li>  Correcting multiple inline links/reflinks in a file </ul>                                                                                                                                                                                                                                                                                                                                                                                                                            	|
| `x:size/medium`  	| 12         	| <ul> <li>  A first-time contribution <li>  Syncing an exercise with problem-specifications (when edits are required) <li>  Adding one or more test case from scratch <li>  Fixing multiple test cases for an exercise <li>  Fixing multiple files in an exercise (edits, typos, code examples, etc.) <li>  Fixing a bug in an exemplar file (with required testing) <li>  Adding mentor notes for an exercise from scratch <li>  Adding clarifying code examples to an exercise <li>  Creating a Hints.md file from scratch <li>  Fixing a small bug in a test runner/analyzer/representer <li>  Adding analyzer comments for a single exericse  </ul>                                                                                                                        	|
| `x:size/large`   	| 30         	| <ul> <li>  Adding a new concept exercise (with test cases) <li>  Adding a new practice exercise (with JinJa template and canonical data) <li>  Adding new concept docs (with links.json) <li>  Substantial edits or re-writes to an existing concept or concept exercise <li>  Required edits across multiple (3-4) exercises.       <ul>       <li> Adding error handling messages and examples across exercises       <li> updating all exercises to use Python 3 idioms,        <li> linting all exercises after instituting new linting and line length rules.       </ul> <li>  New tool selection, configuration, and documentation <li>  New automation (autoresponders, CI scripts, linting scripts, and other repo automation) </ul> 	|
| `x:size/massive` 	| 100        	| <ul> <li>  Creating a test-runner/analyzer/representer from scratch <li>  Major refactors of runners/analyzers/representers <li>  Creating major documentation (contribution guides, installation guides, testing guides, etc) from scratch <li>  Creating CI or test generation automation from scratch </ul>                                                                                                                                                                                                                                                                                                                                                                                                                                	|

**Comment by BethanyG** [comment]
I did the bullets for ease of reading, but once we agree on examples/items, I am happy to make a table that has comma-delimited examples instead.  Also thinking we might want to have links to some of the examples?  Or would that be too much?

**Comment by junedev** [comment]
@BethanyG Thanks a lot for your input! I think the examples are clear enough without links.  
I like the bullet list and also wanted to propose something like this but I read that lists inside a table cell are not part of standard markdown. How did you do this (I can't see the "source code" for your comment)? HTML?

If this is ok which people I would pick a subset of what @BethanyG suggested to not make the example lists too long.

**Comment by BethanyG** [comment]
@junedev   -- let me try to fence the table, and see if it will display.  I did indeed resort to HTML `<ul> and <li> elements`:

```markdown
| Label            	| Reputation 	| Example                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       	|
|------------------	|------------	|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| `x:size/tiny`    	| 3          	| <ul> <li>  Fixing a single typo (includes adding punctuation) <li>  Removing an extra blank lines <li>  Adding a missing `EOL` at the end of a file or files <li>  Adding/changing a header level <li>  Fixing a single link <li>  Changing a single docstring/adding a single comment to code <li>  Changing an in-line link to a reflink <li>  Running prettier to auto-format </ul>                                                                                                                                                                                                                                                                                                                                                        	|
| `x:size/small`   	| 5          	| <ul> <li>  Fixing a single test case/task/code example <li>  Fixing multiple typos in a single file <li>  Fixing multiple headers in a file <li>  Fixing multiple broken links in a file <li>  Adding clarifying language of a few lines to a file <li>  Correcting multiple inline links/reflinks in a file </ul>                                                                                                                                                                                                                                                                                                                                                                                                                            	|
| `x:size/medium`  	| 12         	| <ul> <li>  Syncing an exercise with problem-specifications (when edits are required) <li>  Adding one or more test case from scratch <li>  Fixing multiple test cases for an exercise <li>  Fixing multiple files in an exercise (edits, typos, code examples, etc.) <li>  Fixing a bug in an exemplar file (with required testing) <li>  Adding mentor notes for an exercise from scratch <li>  Adding clarifying code examples to an exercise <li>  Creating a Hints.md file from scratch <li>  Fixing a small bug in a test runner/analyzer/representer <li>  Adding analyzer comments for a single exericse  </ul>                                                                                                                        	|
| `x:size/large`   	| 30         	| <ul> <li>  Adding a new concept exercise (with test cases) <li>  Adding a new practice exercise (with JinJa template and canonical data) <li>  Adding new concept docs (with links.json) <li>  Substantial edits or re-writes to an existing concept or concept exercise <li>  Required edits across multiple (3-4) exercises.       <ul>       <li> Adding error handling messages and examples across exercises       <li> updating all exercises to use Python 3 idioms,        <li> linting all exercises after instituting new linting and line length rules.       </ul> <li>  New tool selection, configuration, and documentation <li>  New automation (autoresponders, CI scripts, linting scripts, and other repo automation) </ul> 	|
| `x:size/massive` 	| 100        	| <ul> <li>  Creating a test-runner/analyzer/representer from scratch <li>  Major refactors of runners/analyzers/representers <li>  Creating major documentation (contribution guides, installation guides, testing guides, etc) from scratch <li>  Creating CI or test generation automation from scratch </ul>                                                                                                                                                                                                                                                                                                                                                                                                                                	|
```

PS -- https://www.tablesgenerator.com/markdown_tables# is my best friend for these hairy tables.  Have yet to find anything better.  😄

**Comment by junedev** [comment]
Since this is hard to review in the diff, here is the rendered version how the section looks now. Note that I also adjusted the text above/below to fit our current practice.

---
### Creating a pull request

By default, `12` reputation is awarded when a pull request is merged that was opened by the user.

Depending on the content of the pull request, a maintainer can award more (or less) reputation by adding one of the following labels to the pull request:

| Label            | Reputation | Examples                                                                                                                                                                                                                                                                                                                                                            |
| ---------------- | ---------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `x:size/tiny`    | 3          | <ul><li>Fixing a single typo or link</li><li>Removing a blank line or adding a line break</li><li>Changing/adding a single code comment</li></ul>                                                                                                                                                                                                                   |
| `x:size/small`   | 5          | <ul><li>Fixing a single test case, task or example</li><li>Fixing multiple typos or links in a single file</li><li>Clarifying content by adding a few lines to a file</li></ul>                                                                                                                                                                                     |
| `x:size/medium`  | 12         | <ul><li>Syncing an exercise with problem-specifications (incl. edits)</li><li>Adding one or more test cases from scratch</li><li>Improving multiple files in an exercise</li><li>Adding mentor notes for an exercise from scratch</li><li>Fixing a small bug in a test runner/analyzer/representer</li><li>Adding analyzer comments for a single exericse</li></ul> |
| `x:size/large`   | 30         | <ul><li>Adding a new concept or practice exercise</li><li>Adding new concept documentation</li><li>Substantial re-writing of an existing concept or exercise</li><li>Adding new CI scripts or other automation</li></ul>                                                                                                                                            |
| `x:size/massive` | 100        | <ul><li>Creating a test-runner, analyzer, representer or generator from scratch</li><li>Major refactors to those tools</li><li>Creating major documentation from scratch (e.g. contribution or testing guides)</li></ul>                                                                                                                                            |

The examples above can serve as rough orientation when to apply which label but maintainers are free to use their own judgement.

- If more than one label is specified, the label with the highest reputation value determines the awarded reputation.
- If a pull request is still open, no reputation is awarded (yet).
- If a pull request is closed _without_ merging, no reputation is awarded.

**Comment by SaschaMann** [comment]
Perhaps you could also add a note that some maintainers/tracks will not add them at all? That way people won't be surprised if their PR doesn't get one (regardless of size).

**Review by ErikSchierboom — APPROVED** [review]
Excellent! I think is a _huge_ improvement over what we currently have.

**Comment by ErikSchierboom** [comment]
@SaschaMann isn't that already covered by:

> By default, 12 reputation is awarded when a pull request is merged that was opened by the user.
> 
> Depending on the content of the pull request, a maintainer can award more (or less) reputation by adding one of the following labels to the pull request:

**Comment by ErikSchierboom** [comment]
Let's merge this and do a potential improvements in a follow PR.

**Comment by SaschaMann** [comment]
@ErikSchierboom It is but maybe it could be more explicit? I'm not sure how important that is though.

**Comment by ErikSchierboom** [comment]
🤷

**Pull request merged**
