### PR TITLE
[Tooling] Remove stack trace from test runner interface

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by iHiD** [comment]
Should we this all or nothing do you think? Are stack traces sometimes useful? I can't remember where we got to in our thinking about this before.

**Comment by ErikSchierboom** [comment]
Me neither. I just noticed that you said something about moving the open PR to this repo. I think the thing we want to guard against is leaking internal file structure information.

**Comment by SaschaMann** [comment]
> I think the thing we want to guard against is leaking internal file structure information.

Is there anything that could be leaked here that couldn't be leaked via the normal failure or debug messages anyway?

**Comment by ErikSchierboom** [comment]
Good question. I'm not sure. I'm definitely not an expert on hardening of servers and such.

**Comment by SleeplessByte** [comment]
Your thinking wasn't necessarily security (that was a pre-docker thing we talked about, and I basically went "it doesn't matter, we can log anything because we can import anything including `path` module etc.).

The primary reason we wanted to do this is because stacktraces unedited look scary and are often pretty unhelpful (because they're littered with library traces/internal calls). I think what we wanted is:

- Simplify the _paths_ to be something like `<solution-dir>/relative/path` instead of `/full/path/to`, as that will include unhelpful ecr specific data,
- When possible or applicable, collapse non-user-code stacks,
- Never show call stacks without context (ie. the error message)

**Comment by ErikSchierboom** [comment]
I've revived this PR and added @SleeplessByte's recommendations (which are great), plus one additional recommendation.

**Pull request merged**
